---
title: "Analise da prova INEP 2015"
author: "Felipe Argolo (a.k.a. 'pingfreud')"
date: "May 6, 2018"
output: html_document
---

## Notas por estado

Dados obtidos do portal oficial INEP (http://portal.inep.gov.br/web/guest/inicio).  
Prova nacional aplicada em 2015. Análises preliminares.  
```{r,include=FALSE,echo = FALSE}
library(xlsx)
library(knitr)
library(purrr)
library(dplyr)
library(car)
library(Amelia)
library(ggplot2)
inep2015_df <- read.xlsx("../data/saeb/estados-saeb-2015-clean-v2.xlsx",sheetIndex=1)
```

```{r pressure, echo=FALSE}
inep2015_df_NA <- inep2015_df %>% 
  purrr::map(function(x) car::recode(x,"0='NA'")) %>%
  as.data.frame()
Amelia::missmap(inep2015_df_NA[,])
```

```{r pressure, echo=FALSE}
inep2015_df %>% filter(localizacao=="Total" & dependecia_adm == "Federal" & X5o_ano_ling_port > 0) %>% select(uf,X5o_ano_ling_port) %>% kable()

ggplot(inep2015_df_NA[inep2015_df_NA$dependecia_adm %in% c("Estadual","Federal","Municipal","Privada"),],aes(x=uf,y=as.numeric(as.character(X5o_ano_ling_port)), color=dependecia_adm))+
  geom_boxplot()+
  scale_x_discrete()
```
